kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/makoto126/quota

steps:
- name: build
  image: golang
  commands:
    - make

- name: docker  
  image: plugins/docker
  settings:
    repo: makoto126/quota
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password